# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "AddLee Now"
client_id = "81054b8def443db2e61797cf88dcc62b"
application_url = "https://guy-soundtrack-manager-involves.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products,write_shipping,read_shipping,write_delivery_customizations,read_orders,read_assigned_fulfillment_orders,unauthenticated_read_customers"

[auth]
redirect_urls = [
  "https://guy-soundtrack-manager-involves.trycloudflare.com/auth/callback",
  "https://guy-soundtrack-manager-involves.trycloudflare.com/auth/shopify/callback",
  "https://guy-soundtrack-manager-involves.trycloudflare.com/api/auth/callback",
  "https://guy-soundtrack-manager-involves.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://guy-soundtrack-manager-involves.trycloudflare.com/api/2.0"
subpath = "affiliates-api-url"
prefix = "tools"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "dev-addlee.myshopify.com"
